// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6s6Q3drE4fHPTqgrTWQdd34aDzWxhjPk',
    appId: '1:189763797518:web:bae653d28fbf555a75f25f',
    messagingSenderId: '189763797518',
    projectId: 'mynotes-4bb3c',
    authDomain: 'mynotes-4bb3c.firebaseapp.com',
    storageBucket: 'mynotes-4bb3c.appspot.com',
    measurementId: 'G-TG9WREF9EZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUtjATToZCZQKzO9hIp8zaEpspExYBtTs',
    appId: '1:189763797518:ios:8ffdb0504cf0f76f75f25f',
    messagingSenderId: '189763797518',
    projectId: 'mynotes-4bb3c',
    storageBucket: 'mynotes-4bb3c.appspot.com',
    iosBundleId: 'com.makingthingsup.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6s6Q3drE4fHPTqgrTWQdd34aDzWxhjPk',
    appId: '1:189763797518:web:22e7494c18a3666375f25f',
    messagingSenderId: '189763797518',
    projectId: 'mynotes-4bb3c',
    authDomain: 'mynotes-4bb3c.firebaseapp.com',
    storageBucket: 'mynotes-4bb3c.appspot.com',
    measurementId: 'G-3M0P2KFLPT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUtjATToZCZQKzO9hIp8zaEpspExYBtTs',
    appId: '1:189763797518:ios:8ffdb0504cf0f76f75f25f',
    messagingSenderId: '189763797518',
    projectId: 'mynotes-4bb3c',
    storageBucket: 'mynotes-4bb3c.appspot.com',
    iosBundleId: 'com.makingthingsup.mynotes',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTCWDZUE9OZUiMaJQ5EFwkUMwlYp248rc',
    appId: '1:189763797518:android:6ac330e3897ee21c75f25f',
    messagingSenderId: '189763797518',
    projectId: 'mynotes-4bb3c',
    storageBucket: 'mynotes-4bb3c.appspot.com',
  );

}